services:

  mysql:
    image: mysql:8
    container_name: maju_jaya_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maju_jaya_dw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  pipeline:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data:/data

volumes:
  mysql_data: